# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
