# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0002_future_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='status',
            field=models.CharField(default='in progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='future',
            name='status',
            field=models.CharField(default='in progress', max_length=30),
        ),
    ]
