# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspects', '0003_auto_20160331_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=200)),
            ],
        ),
    ]
